# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 Alif Semiconductor - All Rights Reserved.
# Use, distribution and modification of this code is permitted under the
# terms stated in the Alif Semiconductor Software License Agreement
#
# You should have received a copy of the Alif Semiconductor Software
# License Agreement with this file. If not, please write to:
# contact@alifsemi.com, or visit: https://alifsemi.com/license
alif_drm-y := alif_drm_driver.o d2d_hw.o

obj-$(CONFIG_DRM_D2D) += alif_drm-y
